version: '3.1'

services:
#   db:
#     image: mysql:5.7
#     container_name: db-mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: bmgtroot
#       MYSQL_DATABASE: book_management
#       MYSQL_USER: bmgt
#       MYSQL_PASSWORD: abc123
#       MYSQL_ROOT_HOST: "%"
#     ports:
#     - "3306:3306"
#     networks:
#       mynet:
#         ipv4_address: 172.20.0.2
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
# networks:
#   mynet:
#       driver: bridge
#       external: true

  db2:
    image: mysql:5.7
    container_name: db-mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bmgtroot
      MYSQL_DATABASE: book_management
      MYSQL_USER: bmgt
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_HOST: "%"
    ports:
    - "3306:3306"
    extra_hosts:
    - "host.docker.internal:host-gateway"